### ISSUE TITLE
Need more Chinese and Korean fonts

### ISSUE THREAD

**Issue by jmlntw** [jmlntw/atom-fonts-cjk#4]
Need more Chinese and Korean fonts. Fonts should be for programming (monospace, distinguishing between the letter "O" and the number "zero", etc.) and its license allows us to use it in this package.

**Comment by jmlntw** [comment]
Yet another great CJK monospaced font here: [**Inziu Iosevka**](https://be5invis.github.io/Iosevka/inziu.html) made by Belleve Invis (@be5invis).

**Comment by be5invis** [comment]
wait
does Atom support ttc?

**Comment by jmlntw** [comment]
Atom doesn't support TTC as webfont. But I think the TTF format should work.

**Comment by be5invis** [comment]
@jmlntw I think you should separate families into multiple packages. And the "Inziu Roboto" is proportional, it should not be included.

**Comment by laughedelic** [comment]
You already have Source Han Sans, but I would recommend you to add [Noto Sans Mono CJK](https://www.google.com/get/noto/help/cjk/) which has latin symbols with half-width of the CJK-characters.
Source Han Sans (Adobe brending) is the same as Noto Sans CJK (Google branding), but as far as I know Adobe doesn't provide a monospaced CJK variation of it, while Google does.

**Comment by jmlntw** [comment]
@laughedelic Noto Sans Mono CJK does'nt distinguish between the letter "O" and the number "zero" which isn't suitable for coding, I think. Also Adobe has Source Han Sans HW, which are as same as Noto Sans Mono CJK.

**Comment by laughedelic** [comment]
> Adobe has Source Han Sans HW, which are as same as Noto Sans Mono CJK.

Thanks, I didn't know it.

> isn't suitable for coding

I think none of the fonts in this package is suitable for coding, however they can be useful for writing markdown documents or any other texts. And I think that usage of Source Han Sans HW / Noto Sans Mono CJK would significantly improve mixed language texts over the currently provided non-monospaced fonts.

**Comment by laughedelic** [comment]
Sorry, I didn't missed the requirements in the top post. I should have probably opened another issue..

**Comment by jmlntw** [comment]
Currently I have no plan to add more new fonts to this package, so I decided to close this issue.

If you have any font suggestions, please open a new issue.
